CREATE TABLE TIPO (
  COD SERIAL PRIMARY KEY,
  DESCRICAO VARCHAR(20) NOT NULL
);

-- -----------------------------------------------------
--ATIVIDADE
-- -----------------------------------------------------
CREATE TABLE ATIVIDADE (
  COD SERIAL PRIMARY KEY,
  TITULO VARCHAR(20) NOT NULL,
  COD_TIPO INT NOT NULL,
  DESCRICAO VARCHAR(150) NOT NULL,
  STATUS CHAR(1) NOT NULL
);

ALTER TABLE ATIVIDADE ADD FOREIGN KEY (COD_TIPO) REFERENCES TIPO(COD);

INSERT INTO TIPO (DESCRICAO) VALUES ('Desenvolvimento');
INSERT INTO TIPO (DESCRICAO) VALUES ('Atividade');
INSERT INTO TIPO (DESCRICAO) VALUES ('Manutenção');
INSERT INTO TIPO (DESCRICAO) VALUES ('Manutenção Urgente');